const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');const {mockCloud,signIn}=require('./mock-cloud.cjs');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1440,height:960}});const cloud=await mockCloud(page),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const due=offset=>{const d=new Date();d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
 cloud.remote={revision:1,data:{tasks:[-1,0,1,7,14,15].map((days,i)=>({id:`t${i}`,title:`Reminder ${days}`,progress:0,due:due(days),category:'Personal',priority:'Medium'})).concat({id:'done',title:'Already completed',progress:100,due:due(0),category:'Personal',priority:'Medium'})}};
 await page.goto('http://127.0.0.1:5174');await signIn(page);await page.locator('.sidebar').getByRole('button',{name:'Notes',exact:true}).click();
 const bell=page.getByRole('button',{name:/^Notifications,/}),panel=page.getByRole('dialog',{name:'Notifications',exact:true});
 await bell.click();await panel.waitFor();assert.equal(await page.locator('.sidebar [aria-current=page]').innerText(),'Notes');assert.equal(await page.locator('.content').getByRole('heading',{name:'Notes',exact:true}).count(),1);assert.equal(await panel.locator('.notification-item').count(),5);assert.equal(await panel.getByText('Already completed').count(),0);assert.equal(await panel.getByText('Reminder 15',{exact:true}).count(),0);
 for(const group of ['Overdue','Today','This Week','Next Week','Later'])assert.equal(await panel.getByRole('region',{name:group,exact:true}).count(),1);
 await page.screenshot({path:'notifications-dark-desktop.png',fullPage:true});await bell.click();assert.equal(await panel.count(),0);await bell.click();await page.mouse.click(300,450);assert.equal(await panel.count(),0);await bell.click();await page.keyboard.press('Escape');assert.equal(await panel.count(),0);assert.equal(await bell.evaluate(el=>el===document.activeElement),true);
 await bell.click();await panel.getByRole('button',{name:'Mark all as read',exact:true}).click();assert.match(await bell.getAttribute('aria-label'),/0 unread/);await panel.locator('.notification-open').filter({hasText:'Reminder 0'}).click();assert.equal(await panel.count(),0);await page.getByLabel('Progress · 0%').focus();await page.keyboard.press('End');await page.getByRole('button',{name:'Save changes',exact:true}).click();await bell.click();assert.equal(await panel.getByText('Reminder 0',{exact:true}).count(),0);assert.equal(await panel.locator('.notification-item').count(),4);
 await panel.getByRole('button',{name:'Dismiss Reminder 7',exact:true}).click();assert.equal(await panel.locator('.notification-item').count(),3);await page.keyboard.press('Escape');assert.equal(await page.locator('.sidebar [aria-current=page]').innerText(),'Notes');
 await page.getByRole('button',{name:'Switch to light mode',exact:true}).click();await page.setViewportSize({width:390,height:844});await bell.click();await panel.waitFor();const box=await panel.boundingBox();assert.ok(box.x>=0&&box.x+box.width<=390&&box.y+box.height<=844);await page.screenshot({path:'notifications-light-mobile.png',fullPage:true});await bell.click();assert.equal(await panel.count(),0);await page.waitForTimeout(1000);assert.equal(cloud.remote.data.tasks.find(t=>t.id==='t1').progress,100);assert.equal(cloud.remote.data.dismissed.length,1);assert.deepEqual(errors,[]);
 console.log('PASS: overlay preserves current page, all deadline groups, badge/read/dismiss, bell/outside/Escape dismissal, completion removes reminders, mobile and both themes.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
