const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');const {mockCloud,signIn}=require('./mock-cloud.cjs');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1440,height:960}});const backend=await mockCloud(page);backend.remote={revision:1,data:{tasks:[{id:'task',title:'Prepare the client presentation',progress:0,category:'Work',priority:'Medium',due:'',subtasks:[]}]}};const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5174');await signIn(page);
 const open=()=>page.getByRole('button',{name:'Manage subtasks Prepare the client presentation',exact:true}).click();await open();const modal=page.getByRole('dialog',{name:'Subtasks',exact:true});
 await page.getByText('One step at a time',{exact:true}).waitFor();for(const title of ['Collect references','Build the outline','Review the final draft']){await page.getByLabel('New subtask',{exact:true}).fill(title);await page.getByLabel('New subtask',{exact:true}).press('Enter');}
 assert.equal(await modal.getByRole('listitem').count(),3);await page.getByRole('checkbox',{name:'Complete Collect references',exact:true}).check();assert.equal(await page.getByRole('progressbar').getAttribute('aria-valuenow'),'33');await page.getByRole('button',{name:'Move Review the final draft up',exact:true}).click();assert.deepEqual(await modal.locator('.subtask-title').evaluateAll(els=>els.map(e=>e.value)),['Collect references','Review the final draft','Build the outline']);
 await page.getByLabel('Edit Build the outline',{exact:true}).fill('Polish the outline');await page.screenshot({path:'subtasks-dark-desktop.png',fullPage:true});await modal.getByRole('button',{name:'Save changes',exact:true}).click();await page.waitForTimeout(1000);assert.equal(backend.remote.data.tasks[0].progress,33);assert.equal(backend.remote.data.tasks[0].subtasks[2].title,'Polish the outline');
 await open();await page.getByRole('button',{name:'Delete subtask Polish the outline',exact:true}).click();await modal.getByRole('button',{name:'Cancel',exact:true}).click();await open();assert.equal(await modal.getByRole('listitem').count(),3);await modal.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.getByRole('button',{name:'Switch to light mode',exact:true}).click();await open();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'subtasks-light-mobile.png',fullPage:true});assert.equal(await modal.evaluate(el=>el.scrollWidth<=el.clientWidth),true);await page.getByRole('button',{name:'Delete subtask Polish the outline',exact:true}).click();await modal.getByRole('button',{name:'Save changes',exact:true}).click();await page.waitForTimeout(1000);assert.equal(backend.remote.data.tasks[0].subtasks.length,2);assert.equal(backend.remote.data.tasks[0].progress,50);await page.reload();await page.locator('.app').waitFor();await open();assert.equal(await modal.getByRole('listitem').count(),2);assert.match(await modal.locator('h2').evaluate(el=>getComputedStyle(el).fontFamily),/DM Sans/);assert.deepEqual(errors,[]);
 console.log('PASS: subtask add/edit/complete/reorder/delete, cancel, saved progress, reload persistence, desktop/mobile and both themes.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
