const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const {mockCloud,signIn}=require('./mock-cloud.cjs');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1440,height:1000}});const backend=await mockCloud(page);const errors=[];page.on('pageerror',e=>errors.push(e.message));const go=async name=>page.getByRole('button',{name,exact:true}).first().click();const fill=async(name,value)=>page.getByLabel(name,{exact:true}).fill(value);const select=async(name,label)=>page.getByLabel(name,{exact:true}).selectOption({label});const balance=async(name,value)=>assert.match(await page.locator('.account-card').filter({has:page.getByRole('heading',{name,exact:true})}).innerText(),new RegExp(value));
try{await page.goto('http://127.0.0.1:5174');await signIn(page);
await go('Clients');await go('Add client');await fill('Client / Business Name','ABC Company');await fill('Contact Person','Alex');await fill('Phone','09123456789');await select('Client Type','Business');await go('Save Client');await go('ABC Company');assert.match(await page.locator('.content').innerText(),/No projects yet/);await go('Create project');assert.equal(await page.getByLabel('Client',{exact:true}).locator('option:checked').innerText(),'ABC Company');await fill('Project Name','Website Redesign');await fill('Start Date','2026-09-01');await fill('Deadline','2026-10-01');await go('Save Project');await go('Website Redesign');
for(const title of ['Design homepage','Build homepage']){await go('Add task');await fill('Task title',title);await page.getByRole('button',{name:'Add task',exact:true}).last().click();}await go('Complete Design homepage');assert.match(await page.locator('.project-completion').innerText(),/50%/);await go('Back to client');assert.match(await page.locator('.v4-metrics').innerText(),/Completed tasks\s+1/);
await go('Finances');for(const [name,type,amount] of [['BPI','Bank','10000'],['GCash','E-wallet','2000'],['Cash','Cash','3500'],['Savings','Savings','15000']]){await go('Add account');await fill('Account Name',name);await select('Account Type',type);await fill('Starting Balance (PHP)',amount);await go('Save Account');}
await go('Add transaction');await fill('What did you buy?','Groceries');await select('Account / Payment Method','GCash');await fill('Amount (PHP)','850');await go('Save Transaction');await balance('GCash','1,150.00');
await go('Add transaction');await select('Transaction Type','Income');await fill('Income source','Client deposit');await select('Account / Payment Method','GCash');await fill('Amount (PHP)','3000');await go('Save Transaction');await balance('GCash','4,150.00');
await go('Add transaction');await select('Transaction Type','Transfer');await select('From Account','BPI');await select('To Account','Cash');await fill('Amount (PHP)','2000');await go('Save Transaction');await balance('BPI','8,000.00');await balance('Cash','5,500.00');assert.match(await page.locator('.finance-stats').innerText(),/32,650.00/);
await go('Edit Groceries');await fill('Amount (PHP)','500');await go('Save Transaction');await balance('GCash','4,500.00');await go('Delete Groceries');await go('Delete');await balance('GCash','5,000.00');await go('Edit Transfer BPI to Cash');await fill('Amount (PHP)','1000');await go('Save Transaction');await balance('BPI','9,000.00');await balance('Cash','4,500.00');
await go('Delete BPI');assert.equal(await page.getByRole('dialog').count(),0);await go('Dismiss notification');await go('Transactions');await go('Transfers');assert.equal(await page.locator('.ledger-row').count(),1);await select('Filter account','Cash');assert.equal(await page.locator('.ledger-row').count(),1);await go('Income');assert.equal(await page.locator('.ledger-row').count(),0);await go('All');await select('Filter account','All accounts');assert.equal(await page.locator('.ledger-row').count(),2);
await page.waitForTimeout(1500);assert.equal(backend.remote.data.transactions.length,2);await page.reload();await page.locator('.app').waitFor();await go('Finances');await balance('GCash','5,000.00');await page.screenshot({path:'v4-finances-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'v4-finances-mobile.png',fullPage:true});await go('Settings');await go('dark');await go('Finances');await page.screenshot({path:'v4-finances-dark.png',fullPage:true});await go('Settings');await go('Sign out');await signIn(page);await go('Finances');await balance('BPI','9,000.00');assert.deepEqual(errors,[]);console.log('PASS V4: client/project details, linked tasks and completion, accounts, expense/income/transfer, ledger editing/deletion, deletion protection, filters, reload, logout/login, dark and mobile layout.');
}finally{await browser.close();}})();
