import React,{useEffect,useRef,useState} from 'react';
import {Plus,X,Pencil,Trash2,ChevronLeft,ChevronRight,Play,Pause,Square,Clock3,Bell,Download} from 'lucide-react';
import {analytics,dayKey,shiftDay,duration,income,money,id,notices,stopTimer} from './domain';
import {supabase} from './supabase';
export function Heading({eyebrow,title,description,action}){return <section className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action}</section>}
export function Empty({children}){return <div className="empty"><p>{children}</p></div>}
export function Dialog({title,onClose,onSubmit,children,submitLabel='Save',wide=false}){const ref=useRef();useEffect(()=>{const previous=document.activeElement;ref.current.showModal();return()=>previous?.focus();},[]);return <dialog className={`modal ${wide ? "modal-wide" : ""}`} aria-label={title} ref={ref} onCancel={onClose}><div className="modal-head"><h2>{title}</h2><button aria-label="Close dialog" className="icon-btn" onClick={onClose}><X size={18}/></button></div><form onSubmit={onSubmit}>{children}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" type="submit">{submitLabel}</button></div></form></dialog>}
export function CalendarPage({data,onEdit,onAdd}){
 const [month,setMonth]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)}),[selected,setSelected]=useState(dayKey());
 const first=dayKey(month),start=shiftDay(first,-month.getDay()),cells=Array.from({length:42},(_,i)=>shiftDay(start,i));
 const dayTasks=data.tasks.filter(t=>t.due===selected);
 const move=n=>setMonth(new Date(month.getFullYear(),month.getMonth()+n,1));
 return <><Heading eyebrow="SEE WHAT'S AHEAD" title="Your calendar." description="A little planning makes space for everything else." action={<button className="primary" onClick={()=>onAdd(selected)}><Plus size={18}/> Add task</button>}/><section className="panel"><div className="panel-head"><h2>{month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><div className="flex gap-2"><button aria-label="Previous month" className="icon-btn" onClick={()=>move(-1)}><ChevronLeft size={18}/></button><button className="secondary" onClick={()=>{setMonth(new Date(new Date().getFullYear(),new Date().getMonth(),1));setSelected(dayKey());}}>Today</button><button aria-label="Next month" className="icon-btn" onClick={()=>move(1)}><ChevronRight size={18}/></button></div></div><div className="calendar-week">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><span key={d}>{d}</span>)}</div><div className="calendar-month">{cells.map(key=>{const list=data.tasks.filter(t=>t.due===key);return <button key={key} aria-label={`${key}, ${list.length} tasks`} aria-pressed={key===selected} className={`calendar-cell ${key===selected?'selected':''} ${key===dayKey()?'is-today':''} ${key.slice(0,7)!==first.slice(0,7)?'outside':''}`} onClick={()=>setSelected(key)}><span>{Number(key.slice(-2))}</span>{list.slice(0,2).map(t=><small key={t.id} className={t.progress===100?'finished':''}>{t.title}</small>)}{list.length>2&&<small>+{list.length-2} more</small>}</button>})}</div></section><section className="panel mt-4"><div className="panel-head"><h2>{new Date(selected+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</h2><span className="tag">{dayTasks.length} tasks</span></div>{dayTasks.length?dayTasks.map(t=><button className="agenda-row" key={t.id} onClick={()=>onEdit(t)}><span>{t.title}</span><span className="muted">{t.category} · {t.progress}% <Pencil size={13}/></span></button>):<Empty>No deadlines on this day.</Empty>}</section></>;
}
export function useTimer(data,update,notify){
 const [now,setNow]=useState(Date.now());
 useEffect(()=>{const interval=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(interval);},[]);
 useEffect(()=>{const t=data.timer;if(t?.kind==='focus'&&(t.elapsed||0)+(t.startedAt?(now-t.startedAt)/1000:0)>=t.duration){update(d=>d.timer?.id===t.id?stopTimer(d,t.startedAt?t.startedAt+(t.duration-(t.elapsed||0))*1000:now,true):d);notify('Focus session complete. Take a well-earned break.');}},[now,data.timer]);
 return now;
}
export function FocusPage({data,update,now,notify}){
 const [kind,setKind]=useState('focus'),[minutes,setMinutes]=useState(25),[taskId,setTaskId]=useState('');const timer=data.timer;
 const elapsed=timer?Math.max(0,(timer.elapsed||0)+(timer.startedAt?(now-timer.startedAt)/1000:0)):0;
 const display=timer?(timer.kind==='focus'?Math.max(0,timer.duration-elapsed):elapsed):Number(minutes)*60;
 const start=()=>{if(data.timer)return;const t=data.tasks.find(t=>t.id===taskId);update({timer:{id:id(),kind,duration:Number(minutes)*60,elapsed:0,startedAt:Date.now(),taskId,label:t?.title||(kind==='focus'?'Focus session':'Time tracking')}});};
 const pause=()=>update(d=>({...d,timer:d.timer?{...d.timer,elapsed:(d.timer.elapsed||0)+(d.timer.startedAt?(Date.now()-d.timer.startedAt)/1000:0),startedAt:d.timer.startedAt?null:Date.now()}:null}));
 return <><Heading eyebrow="ONE THING AT A TIME" title="Find your focus." description="Protect your attention. Give your next task a little time."/><div className="settings-grid"><section className="panel focus-panel"><div className="flex justify-center gap-2">{['focus','tracker'].map(k=><button key={k} className={`filter ${(timer?.kind||kind)===k?'selected':''}`} disabled={!!timer} onClick={()=>setKind(k)}>{k==='focus'?'Focus timer':'Time tracker'}</button>)}</div><div className="timer-digits" role="timer" aria-label="Timer remaining or elapsed">{duration(display)}</div><p className="muted">{timer?timer.label:kind==='focus'?'Make a little room for deep work.':'Track the time you put into your work.'}</p>{!timer&&<div className="timer-setup"><label className="field">Link to task<select value={taskId} onChange={e=>setTaskId(e.target.value)}><option value="">No task</option>{data.tasks.filter(t=>t.progress<100).map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></label>{kind==='focus'&&<label className="field">Focus minutes<input type="number" min="1" max="180" value={minutes} onChange={e=>setMinutes(e.target.value)}/></label>}</div>}<div className="flex justify-center gap-3 mt-6">{timer?<><button className="primary" onClick={pause}>{timer.startedAt?<Pause size={18}/>:<Play size={18}/>} {timer.startedAt?'Pause':'Resume'}</button><button className="secondary flex items-center gap-2" onClick={()=>{update(d=>stopTimer(d));notify('Session saved to your time log.');}}><Square size={16}/> Stop & save</button></>:<button className="primary" disabled={!Number(minutes)||Number(minutes)<1||Number(minutes)>180} onClick={start}><Play size={18}/> Start {kind==='focus'?'focus':'tracking'}</button>}</div><p className="muted text-xs mt-6">Timers survive navigation and reloads. Closing the app does not pause an active timer.</p></section><section className="panel"><div className="panel-head"><h2>Time well spent</h2><Clock3 size={20}/></div><div className="stat-value">{duration(data.sessions.reduce((s,t)=>s+t.seconds,0))}</div><p className="muted text-sm mb-4">Total recorded time</p>{data.sessions.length?data.sessions.slice().reverse().slice(0,10).map(s=><div className="record-row" key={s.id}><div><strong>{s.label}</strong><small>{new Date(s.endedAt).toLocaleString()} · {s.kind}</small></div><span>{duration(s.seconds)}</span><button className="more" aria-label={`Delete time entry ${s.label}`} onClick={()=>update({sessions:data.sessions.filter(t=>t.id!==s.id)})}><Trash2 size={15}/></button></div>):<Empty>Your completed sessions will appear here.</Empty>}</section></div></>;
}
export function AnalyticsPage({data}){const a=analytics(data),max=Math.max(1,...a.days.map(d=>d.count));return <><Heading eyebrow="PROGRESS, NOT PERFECTION" title="Look how far you've come." description="A real picture of your week, built from your activity."/><section className="stat-grid">{[['Completed this week',a.completed],['Current streak',`${a.streak} days`],['Time this week',duration(a.seconds)],['Overdue tasks',a.overdue]].map(([label,value])=><div className="stat-card" key={label}><div className="stat-title">{label}</div><div className="stat-value mt-4">{value}</div></div>)}</section><div className="settings-grid"><section className="panel"><h2>Weekly activity</h2><p className="muted text-sm mt-2">Week of {a.start} · completed tasks</p><div className="activity-chart">{a.days.map(d=><div key={d.key}><strong>{d.count}</strong><div className="activity-bar" style={{height:`${d.count/max*150+3}px`}}/><small>{new Date(d.key+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})}</small></div>)}</div></section><section className="panel"><h2>Your weekly summary</h2><p className="summary-copy">You completed <strong>{a.completed} tasks</strong> and recorded <strong>{Math.round(a.seconds/60)} minutes</strong> this week.</p><p className="muted text-sm">{a.overdue?`${a.overdue} overdue tasks could use a little attention.`:'Your deadlines are looking clear.'}</p><div className="quote">{a.streak?'Keep your rhythm. A little every day adds up.':'Start a streak by completing a task today.'}</div><p className="muted text-xs mt-4">Weeks begin Monday. Streaks count consecutive local dates with a completed task, ending today or yesterday. Imported tasks without completion dates are excluded.</p></section></div></>}
export function AccountPanel({workspace,notify}){const [mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false);
 const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(workspace.data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`karibok-backup-${dayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="panel settings-panel"><h2>Account & sync</h2><p className="muted">{supabase?workspace.user?.email||'Sign in to carry your workspace across devices.':'Local mode is active. Supabase connection setup is ready for when you want cloud sync.'}</p><p className="sync-status" role="status">{workspace.status}</p>{supabase&&(workspace.user?<div className="flex flex-wrap gap-2 my-4"><button className="secondary" onClick={()=>workspace.sync()}>Sync now</button>{workspace.conflict&&<button className="secondary" onClick={()=>workspace.reload()}>Load cloud version</button>}<button className="secondary" onClick={()=>workspace.signOut().catch(e=>notify(e.message))}>Sign out</button></div>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const result=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.origin}});if(result.error)throw result.error;notify(mode==='signup'?'Check your email to confirm your account, then sign in.':'Signed in.');setPassword('');}catch(e){notify(e.message);}finally{setBusy(false);}}}><label className="field">Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field">Password<input type="password" minLength={8} autoComplete={mode==='login'?'current-password':'new-password'} required value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="flex items-center gap-3"><button className="primary" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</button><button className="text-btn" type="button" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Create an account':'Already registered?'}</button></div></form>)}<button className="secondary flex gap-2 items-center mt-5" onClick={download}><Download size={16}/> Export backup</button>{workspace.conflict&&<p className="muted text-xs mt-3">Export your local draft first. Loading cloud data keeps an additional recovery copy in this browser.</p>}</section>
}
export function CategoryManager({data,update,notify}){const [value,setValue]=useState(''),[editing,setEditing]=useState(null);return <section className="panel settings-panel"><h2>Categories</h2><p className="muted">Organize each part of your day.</p><form className="flex gap-2 my-4" onSubmit={e=>{e.preventDefault();const name=value.trim();if(!name)return;if(name.toLowerCase()==='all'||data.categories.some(c=>c!==editing&&c.toLowerCase()===name.toLowerCase())){notify('That category name is already in use.');return;}update(d=>({...d,categories:editing?d.categories.map(c=>c===editing?name:c):[...d.categories,name],tasks:d.tasks.map(t=>t.category===editing?{...t,category:name}:t)}));setValue('');setEditing(null);}}><input className="category-input" aria-label="Category name" required maxLength={30} value={value} onChange={e=>setValue(e.target.value)} placeholder="e.g. Side projects"/><button className="primary">{editing?'Save':'Add'}</button>{editing&&<button className="secondary" type="button" onClick={()=>{setEditing(null);setValue('');}}>Cancel</button>}</form>{data.categories.map(c=><div className="record-row" key={c}><span>{c}</span><div className="flex gap-2"><button className="more" aria-label={`Rename category ${c}`} onClick={()=>{setEditing(c);setValue(c);}}><Pencil size={15}/></button><button className="more" aria-label={`Delete category ${c}`} onClick={()=>{if(data.categories.length===1||data.tasks.some(t=>t.category===c)){notify('Keep at least one category. Move linked tasks before deleting a category.');return;}update({categories:data.categories.filter(v=>v!==c)});if(editing===c){setEditing(null);setValue('');}}}><Trash2 size={15}/></button></div></div>)}</section>}


