import {UtangPage} from './UtangPage';
import React, { useEffect, useState } from 'react';
import { Plus, ArrowRight, ArrowDownLeft, ArrowUpRight, ArrowLeftRight, WalletCards } from 'lucide-react';
import { Heading, Empty, Dialog } from './features';
import { id, dayKey, income, money } from './domain';
import { ACCOUNT_TYPES, EXPENSE_CATEGORIES, INCOME_CATEGORIES, parseCents, financeSummary, validateAccount, validateTransaction, deletionReason, upsert } from './v4';
import { Field, RecordActions, DeleteDialog, centsMoney } from './v4ui';

export function FinancePage({ data, update, notify, quickAdd, onQuickAddHandled }) {
  const [tab,setTab]=useState('Overview');
  const [typeFilter,setTypeFilter]=useState('all');
  const [accountFilter,setAccountFilter]=useState('');
  const [month,setMonth]=useState(dayKey().slice(0,7));
  const [editor,setEditor]=useState(null);
  const [deleting,setDeleting]=useState(null);
  const [error,setError]=useState('');
  const current=financeSummary(data,dayKey().slice(0,7));
  const summary=financeSummary(data,month);
  const accountName=id=>data.accounts.find(a=>a.id===id)?.name||'Unavailable account';
  const open=(kind,value)=>{setError('');setEditor({kind,value:{...value}});};
  const newAccount=()=>open('accounts',{id:id(),name:'',type:'Bank',startingBalance:'0.00',notes:'',color:'#3b82f6'});
  const newTransaction=()=>open('transactions',{id:id(),type:'expense',description:'',amount:'',accountId:data.accounts[0]?.id||'',toAccountId:'',category:'Food',paymentMethod:'Online Payment',paymentRecorded:true,date:dayKey(),notes:''});
  useEffect(() => {
    if (!quickAdd) return;
    if (quickAdd.kind === 'transaction') { setTab('Transactions'); newTransaction(); onQuickAddHandled?.(); }
    if (quickAdd.kind === 'utang') { setTab('Utang'); }
  }, [quickAdd]);
  const editAccount=a=>open('accounts',{...a,startingBalance:(a.startingBalanceCents/100).toFixed(2)});
  const editTransaction=t=>open('transactions',{...t,amount:(t.amountCents/100).toFixed(2)});
  const change=(key,value)=>setEditor(e=>({...e,value:{...e.value,[key]:value}}));
  const changeType=type=>setEditor(e=>({...e,value:{...e.value,type,paymentMethod:type==='expense'?'Online Payment':'',paymentRecorded:true,customPaymentMethod:'',category:type==='expense'?'Food':type==='income'?'Freelance':'',toAccountId:'',description:''}}));
  const requestDelete=(kind,record)=>{const reason=deletionReason(data,kind,record.id);if(reason)return notify(reason);setDeleting({kind,record});};
  const history=data.transactions.filter(t=>(typeFilter==='all'||t.type===typeFilter)&&(!accountFilter||t.accountId===accountFilter||t.toAccountId===accountFilter)).slice().sort((a,b)=>b.date.localeCompare(a.date)||(b.createdAt||'').localeCompare(a.createdAt||''));
  const transactionRow=t=><article className={`ledger-row ledger-${t.type}`} key={t.id}>
    <div className="ledger-icon" style={{color:data.accounts.find(a=>a.id===t.accountId)?.color}}>{t.type==='income'?<ArrowDownLeft size={18}/>:t.type==='expense'?<ArrowUpRight size={18}/>:<ArrowLeftRight size={18}/>}</div>
    <div className="ledger-description"><strong>{t.type==='transfer'?`${accountName(t.accountId)} → ${accountName(t.toAccountId)}`:t.description}</strong><span>{t.type==='transfer'?'Transfer':`${t.paymentMethod==='COD'&&t.paymentRecorded===false?'COD · Awaiting payment':accountName(t.accountId)} · ${t.category}${t.paymentMethod?' · '+(t.paymentMethod==='Other'?t.customPaymentMethod:t.paymentMethod):''}`} · {t.date}</span>{t.notes&&<p>{t.notes}</p>}</div>
    <div className="ledger-amount"><strong>{t.type==='income'?'+':t.type==='expense'?'−':''}{centsMoney(t.amountCents)}</strong><small>{t.paymentMethod==='COD'&&t.paymentRecorded===false?'COD · Unpaid':t.type==='transfer'?'Transfer':t.type==='income'?'Income':'Expense'}</small></div>
    <RecordActions label={t.type==='transfer'?`Transfer ${accountName(t.accountId)} to ${accountName(t.toAccountId)}`:t.description} onEdit={()=>editTransaction(t)} onDelete={()=>requestDelete('transactions',t)}/>
  </article>;
  return <>
    <Heading eyebrow="FINANCES · MONEY" title="Every peso, a place." description="Where your money is. What you spend. What you keep." action={<div className="v4-actions"><button className="secondary" onClick={newAccount}><Plus size={16}/> Add account</button><button className="primary" onClick={newTransaction}><Plus size={17}/> Add transaction</button></div>}/>
    <div className="v4-tabs" aria-label="Finance views">{['Overview','Accounts','Transactions','Utang','Project payments'].map(name=><button className={`filter ${tab===name?'selected':''}`} aria-pressed={tab===name} key={name} onClick={()=>setTab(name)}>{name}</button>)}</div>
    {tab==='Utang'?<UtangPage data={data} update={update} quickAdd={quickAdd} onQuickAddHandled={onQuickAddHandled}/>:tab==='Project payments'?<ProjectPayments data={data} update={update} notify={notify}/>:<>
      <section className="stat-grid finance-stats">{[['Total Balance',current.total],['Available Cash',current.cash],['Total Savings',current.savings],["This Month’s Income",current.income],["This Month’s Expenses",current.expenses]].map(([label,value])=><div className="stat-card" key={label}><div className="stat-title">{label}</div><div className="stat-value">{centsMoney(value)}</div></div>)}</section>
      {['Overview','Accounts'].includes(tab)?<>
        <div className="v4-section-heading"><h2>Accounts</h2><span className="muted text-xs">Cash and Savings totals follow the account type.</span></div>
        {data.accounts.length?<div className="accounts-grid">{data.accounts.map(a=><article className="panel account-card" key={a.id} data-account-id={a.id} style={{'--account-color':a.color||'#64748b'}}><div className="record-title"><div><div className="account-type"><WalletCards size={15}/>{a.type}</div><h2>{a.name}</h2></div><RecordActions label={a.name} onEdit={()=>editAccount(a)} onDelete={()=>requestDelete('accounts',a)}/></div><strong className="account-balance">{centsMoney(current.balances[a.id])}</strong>{a.notes&&<p className="muted text-xs mt-3">{a.notes}</p>}</article>)}</div>:<section className="panel"><Empty>No accounts yet. Add a bank, e-wallet, cash wallet, or savings account.</Empty><button className="primary empty-action" onClick={newAccount}><Plus size={16}/> Add your first account</button></section>}
        {tab==='Overview'&&<><div className="finance-summary-grid"><section className="panel"><div className="panel-head"><h2>Monthly summary</h2><label className="month-filter"><span className="sr-only">Summary month</span><input aria-label="Summary month" type="month" value={month} onChange={e=>e.target.value&&setMonth(e.target.value)}/></label></div><p className="muted text-sm">{new Date(month+'-01T12:00:00').toLocaleDateString(undefined,{month:'long',year:'numeric'})}</p><dl className="money-summary">{[['Income',summary.income],['Expenses',summary.expenses],['Net',summary.net]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{centsMoney(value)}</dd></div>)}</dl><p className="muted text-xs">Transfers and starting balances are excluded from income and expenses.</p></section><section className="panel"><h2>Spending by category</h2>{Object.keys(summary.spending).length?Object.entries(summary.spending).sort((a,b)=>b[1]-a[1]).map(([category,cents])=><div className="progress-stat" key={category}><div><span>{category}</span><strong>{centsMoney(cents)}</strong></div><div className="progress-track"><div className="progress-fill" style={{width:`${cents/summary.expenses*100}%`}}/></div></div>):<Empty>No expenses recorded for this month.</Empty>}</section></div>
        <section className="panel mt-4"><div className="panel-head"><h2>Recent transactions</h2><button className="text-btn" onClick={()=>setTab('Transactions')}>View all <ArrowRight size={15}/></button></div>{data.transactions.length?data.transactions.slice().sort((a,b)=>b.date.localeCompare(a.date)||(b.createdAt||'').localeCompare(a.createdAt||'')).slice(0,5).map(transactionRow):<Empty>No transactions yet. Record an expense, income, or transfer to see your balances update.</Empty>}</section></>}
      </>:<section className="panel"><div className="panel-head"><h2>Transaction history</h2><span className="muted text-sm">{history.length} records</span></div><div className="ledger-filters"><div className="v4-tabs">{[['all','All'],['income','Income'],['expense','Expenses'],['transfer','Transfers']].map(([key,label])=><button className={`filter ${typeFilter===key?'selected':''}`} aria-pressed={typeFilter===key} key={key} onClick={()=>setTypeFilter(key)}>{label}</button>)}</div><Field label="Filter account" value={accountFilter} onChange={setAccountFilter} options={[{value:'',label:'All accounts'},...data.accounts.map(a=>({value:a.id,label:a.name}))]}/></div>{history.length?history.map(transactionRow):<Empty>No transactions match this view.</Empty>}</section>}
    </>}
    {editor&&<Dialog title={`${data[editor.kind].some(r=>r.id===editor.value.id)?'Edit':'Add'} ${editor.kind==='accounts'?'account':'transaction'}`} submitLabel={editor.kind==='accounts'?'Save Account':'Save Transaction'} wide onClose={()=>setEditor(null)} onSubmit={e=>{e.preventDefault();setError('');try{const value={...editor.value};if(editor.kind==='accounts'){value.name=value.name.trim();value.startingBalanceCents=parseCents(value.startingBalance,true);delete value.startingBalance;validateAccount(value);}else{value.amountCents=parseCents(value.amount);delete value.amount;value.description=value.description.trim();if(value.type==='transfer'){value.category='';value.description='Transfer';}else value.toAccountId='';if(value.type==='expense'&&value.paymentMethod==='COD'&&value.paymentRecorded===false)value.accountId='';value.createdAt=value.createdAt||new Date().toISOString();validateTransaction(value,data);}update(d=>{editor.kind==='accounts'?validateAccount(value):validateTransaction(value,d);return upsert(d,editor.kind,value);});setEditor(null);}catch(e){setError(e.message);}}}>
      {editor.kind==='accounts'?<><Field label="Account Name" required value={editor.value.name} onChange={v=>change('name',v)}/><div className="form-grid"><Field label="Account Type" value={editor.value.type} onChange={v=>change('type',v)} options={ACCOUNT_TYPES}/><Field label="Starting Balance (PHP)" inputMode="decimal" required value={editor.value.startingBalance} onChange={v=>change('startingBalance',v)}/></div><p className="muted text-xs mb-4">Starting balance is the amount before your recorded transactions. Editing it recalculates this account’s current balance.</p><fieldset className="account-colors"><legend>Account color</legend><div className="v4-actions">{['#dc2626','#2563eb','#16a34a','#9333ea','#ea580c','#64748b'].map(color=><button type="button" key={color} aria-label={'Account color '+color} aria-pressed={editor.value.color===color} style={{background:color}} onClick={()=>change('color',color)}/>)}<input aria-label="Custom account color" type="color" value={editor.value.color||'#64748b'} onChange={e=>change('color',e.target.value)}/></div><p className="muted text-xs">Only this account’s appearance changes.</p></fieldset><Field label="Notes" multiline value={editor.value.notes} onChange={v=>change('notes',v)}/></>:<>
        <Field label="Transaction Type" value={editor.value.type} onChange={changeType} options={[{value:'expense',label:'Expense'},{value:'income',label:'Income'},{value:'transfer',label:'Transfer'}]}/>
        {editor.value.type!=='transfer'&&<Field label={editor.value.type==='expense'?'What did you buy?':'Income source'} required value={editor.value.description} onChange={v=>change('description',v)}/>}
        {editor.value.type==='expense'&&<><Field label="Payment Method" value={editor.value.paymentMethod||''} onChange={v=>{change('paymentMethod',v);change('paymentRecorded',v!=='COD');change('accountId','');}} options={[{value:'',label:'Account payment (existing)'},'Cash','Bank','E-wallet','COD','Online Payment','Other']}/>{editor.value.paymentMethod==='Other'&&<Field label="Specify payment method" required value={editor.value.customPaymentMethod||''} onChange={v=>change('customPaymentMethod',v)}/>} {editor.value.paymentMethod==='COD'&&<label className="v4-copy"><input type="checkbox" checked={editor.value.paymentRecorded!==false} onChange={e=>{change('paymentRecorded',e.target.checked);change('accountId','');}}/> Payment recorded</label>}</>}
        <div className="form-grid"><Field disabled={editor.value.type==='expense'&&editor.value.paymentMethod==='COD'&&editor.value.paymentRecorded===false} label={editor.value.type==='transfer'?'From Account':'Account / Payment Method'} required value={editor.value.accountId} onChange={v=>change('accountId',v)} options={[{value:'',label:'Choose an account'},...data.accounts.filter(a=>editor.value.type!=='expense'||!['Cash','Bank','E-wallet'].includes(editor.value.paymentMethod)||a.type===editor.value.paymentMethod).map(a=>({value:a.id,label:a.name}))]}/>{editor.value.type==='transfer'?<Field label="To Account" required value={editor.value.toAccountId} onChange={v=>change('toAccountId',v)} options={[{value:'',label:'Choose an account'},...data.accounts.map(a=>({value:a.id,label:a.name}))]}/>:<Field label="Category" value={editor.value.category} onChange={v=>change('category',v)} options={editor.value.type==='expense'?EXPENSE_CATEGORIES:INCOME_CATEGORIES}/>}</div>
        <div className="form-grid"><Field label="Amount (PHP)" inputMode="decimal" required value={editor.value.amount} onChange={v=>change('amount',v)}/><Field label="Date" type="date" required value={editor.value.date} onChange={v=>change('date',v)}/></div>
        {editor.value.type==='transfer'&&<p className="muted text-xs mb-4">A transfer moves money between two accounts. It does not count as income or an expense.</p>}<Field label="Notes" multiline value={editor.value.notes} onChange={v=>change('notes',v)}/>
      </>}{error&&<p className="auth-feedback auth-error" role="alert">{error}</p>}
    </Dialog>}
    {deleting&&<DeleteDialog label={deleting.record.name||deleting.record.description} description={deleting.kind==='transactions'?'The transaction will be removed and affected account balances recalculated.':'The account will be removed. Accounts with transactions cannot be deleted.'} onClose={()=>setDeleting(null)} onDelete={()=>{try{update(d=>{const reason=deletionReason(d,deleting.kind,deleting.record.id);if(reason)throw Error(reason);return {...d,[deleting.kind]:d[deleting.kind].filter(r=>r.id!==deleting.record.id)};});setDeleting(null);}catch(e){notify(e.message);setDeleting(null);}}}/>}
  </>;
}

// Existing billed/paid/unpaid records remain separate from the cash ledger.
// Nothing is converted into income without a real receiving account and transaction.
function ProjectPayments({data,update,notify}) {
  const [edit,setEdit]=useState(null),[error,setError]=useState(''),[deleting,setDeleting]=useState(null);
  const totals=income(data.payments);
  return <><section className="panel"><div className="panel-head"><div><h2>Project payments</h2><p className="muted text-sm mt-3">Keep track of billed, paid, and unpaid work. These records do not change account balances; record money received as an income transaction.</p></div><button className="primary" disabled={!data.projects.length} onClick={()=>{setError('');setEdit({id:id(),projectId:data.projects[0]?.id||'',description:'',amount:'',due:dayKey(),paid:false,paidAt:null});}}><Plus size={16}/> Add payment</button></div><div className="v4-metrics">{[['Billed',totals.billed],['Paid',totals.paid],['Unpaid',totals.unpaid]].map(([label,amount])=><div key={label}><span>{label}</span><strong>{money(amount)}</strong></div>)}</div>{!data.projects.length&&<p className="muted text-sm">Create a project before adding a payment record.</p>}{data.payments.length?data.payments.map(p=><article className="payment-row" key={p.id}><div className="record-title"><h2>{p.description}</h2><RecordActions label={p.description} onEdit={()=>{setError('');setEdit({...p});}} onDelete={()=>setDeleting(p)}/></div><div className="payment-details"><div><p>{data.projects.find(x=>x.id===p.projectId)?.title||'Unlinked project'}</p><small className="muted">Due {p.due||'not set'}</small></div><strong>{money(Number(p.amount))}</strong><button className={`filter ${p.paid?'selected':''}`} aria-label={`${p.paid?'Mark unpaid':'Mark paid'} ${p.description}`} onClick={()=>update(d=>({...d,payments:d.payments.map(x=>x.id===p.id?{...x,paid:!x.paid,paidAt:x.paid?null:dayKey()}:x)}))}>{p.paid?'Paid':'Unpaid'}</button></div></article>):<Empty>No project payment records yet.</Empty>}</section>
    {edit&&<Dialog title="Project payment" submitLabel="Save Payment" onClose={()=>setEdit(null)} onSubmit={e=>{e.preventDefault();try{const value={...edit,description:edit.description.trim(),amount:parseCents(edit.amount)/100};if(!value.description||value.amount<=0)throw Error('Enter a description and a positive amount.');update(d=>{if(!d.projects.some(p=>p.id===value.projectId))throw Error('Choose an existing project.');return upsert(d,'payments',value);});setEdit(null);}catch(e){setError(e.message);}}}><Field label="Payment description" required value={edit.description} onChange={v=>setEdit({...edit,description:v})}/><Field label="Project" value={edit.projectId} options={data.projects.map(p=>({value:p.id,label:p.title}))} onChange={v=>setEdit({...edit,projectId:v})}/><Field label="Amount (PHP)" inputMode="decimal" required value={edit.amount} onChange={v=>setEdit({...edit,amount:v})}/><Field label="Payment deadline" type="date" value={edit.due} onChange={v=>setEdit({...edit,due:v})}/>{error&&<p role="alert">{error}</p>}</Dialog>}
    {deleting&&<DeleteDialog label={deleting.description} onClose={()=>setDeleting(null)} onDelete={()=>{update(d=>({...d,payments:d.payments.filter(p=>p.id!==deleting.id)}));setDeleting(null);}}/>}
  </>;
}
