import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { LayoutDashboard, CheckSquare, Settings, Plus, Search, CircleCheck, Circle, Trash2, Pencil, X, Clock3, Layers, TrendingUp, Sun, Moon, Monitor, Upload, Sparkles } from 'lucide-react';
import './styles.css';
import './depth.css';
import './v4.css';
import {WorkPage} from './WorkPage';
import {FinancePage} from './FinancePage';
import {CalendarDays,BarChart3,FolderKanban,Users,WalletCards,Bell,Timer} from 'lucide-react';
import {useWorkspace} from './useWorkspace';
import {SplashScreen, AuthScreen, WorkspaceLoading} from './AuthFlow';
import {saveTask,notices} from './domain';
import {CalendarPage,FocusPage,AnalyticsPage,NotificationsPage,AccountPanel,CategoryManager,useTimer} from './features';
const dateKey = (offset=0) => { const d=new Date(); d.setDate(d.getDate()+offset); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const seed = [
 ['Finish database project','School','Database Management',75,0,'High'],
 ['Client poster revision','Freelance','Client A — Branding',60,1,'High'],
 ['Submit Web Development activity','School','Web Development',40,3,'Medium'],
 ['Send final logo files','Freelance','Client B — Logo',100,4,'Medium'],
 ['Buy school supplies','Personal','',0,5,'Low']
].map(([title,category,project,progress,offset,priority],i)=>({id:String(i),title,category,project,progress,due:dateKey(offset),priority}));
const defaults={tasks:seed,categories:['School','Work','Freelance','Personal'],name:'Kaycee',photo:'',theme:'system',accent:'#8b3f2f'};
function useAppearance(data) {
 useEffect(()=>{const media=matchMedia('(prefers-color-scheme: dark)'); const apply=()=>{document.documentElement.dataset.theme=data.theme==='system'?(media.matches?'dark':'light'):data.theme;};apply();media.addEventListener('change',apply);document.documentElement.style.setProperty('--accent',data.accent);const rgb=data.accent.slice(1).match(/../g)?.map(x=>parseInt(x,16))||[139,63,47];const lum=rgb.map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);document.documentElement.style.setProperty('--on-accent',lum>.179?'#171717':'#ffffff');return()=>media.removeEventListener('change',apply);},[data.theme,data.accent]);
}
function App() {
 const workspace = useWorkspace(defaults);
 const [splash, setSplash] = useState(true);
 useAppearance(workspace.data);
 useEffect(() => {
   const timer = setTimeout(() => setSplash(false), 3000);
   return () => clearTimeout(timer);
 }, []);
 if (splash) return <SplashScreen />;
 if (!workspace.authChecked) return <WorkspaceLoading workspace={workspace} />;
 if (!workspace.user) return <AuthScreen sessionError={workspace.authError} onRetry={() => workspace.retry()} />;
 if (!workspace.ready) return <WorkspaceLoading workspace={workspace} />;
 return <WorkspaceApp key={workspace.user.id} workspace={workspace} />;
}
function WorkspaceApp({workspace}) {
 const {data,update}=workspace;
 const [page,setPage]=useState('Dashboard'),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[editor,setEditor]=useState(null),[message,setMessage]=useState('');

 const now=useTimer(data,update,setMessage);
 useEffect(()=>{window.scrollTo({top:0});},[page]);
 useEffect(()=>{if(!data.categories.includes(filter)&&filter!=='All')setFilter('All');},[data.categories,filter]);
 useEffect(()=>{if(!data.notificationsEnabled||!('Notification' in window)||Notification.permission!=='granted')return;for(const notice of notices(data)){const key='karibok-notified-'+(workspace.user?.id||'guest')+'-'+notice.id;try{if(!localStorage.getItem(key)){new Notification(notice.title,{body:notice.detail});localStorage.setItem(key,'1');}}catch{}}},[data.tasks,data.sessions,data.notificationsEnabled,dateKey()]);

 const tasks=data.tasks.filter(t=>(filter==='All'||t.category===filter)&&`${t.title} ${t.project} ${t.category}`.toLowerCase().includes(query.toLowerCase()));
 const complete=data.tasks.filter(t=>t.progress===100).length;
 const average=list=>list.length?Math.round(list.reduce((s,t)=>s+t.progress,0)/list.length):0;
 const edit=t=>setEditor(t?{...t}:{id:crypto.randomUUID(),title:'',category:data.categories[0],project:'',projectId:'',recurrence:'none',priority:'Medium',due:'',progress:0});
 const toggle=id=>update(d=>{const t=d.tasks.find(t=>t.id===id);return saveTask(d,{...t,progress:t.progress===100?(t.previousProgress||0):100,previousProgress:t.progress===100?0:t.progress});});
 const remove=id=>{update({tasks:data.tasks.filter(t=>t.id!==id)});setMessage('Task deleted.');};
 const upload=e=>{const file=e.target.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>2*1024*1024){setMessage('Choose a JPG, PNG, or WebP image under 2 MB.');return;}const reader=new FileReader();reader.onload=()=>update({photo:reader.result});reader.onerror=()=>setMessage('The image could not be read.');reader.readAsDataURL(file);};
 const avatar=<span className="avatar">{data.photo?<img src={data.photo} alt="Profile"/>:data.name.slice(0,1).toUpperCase()}</span>;
 const row=t=><div className={`task-row ${t.progress===100?'done':''}`} key={t.id}><button className="check" aria-label={`${t.progress===100?'Reopen':'Complete'} ${t.title}`} onClick={()=>toggle(t.id)}>{t.progress===100?<CircleCheck size={21}/>:<Circle size={21}/>}</button><div className="task-info"><strong>{t.title}</strong><span>{t.project||t.category} · {t.progress}%</span><div className="progress-track mt-2"><div className="progress-fill" style={{width:`${t.progress}%`}}/></div></div><span className="tag">{t.category}</span><span className={`priority ${t.priority.toLowerCase()}`}>{t.priority}</span><span className={`due ${t.due&&t.due<dateKey()&&t.progress<100?'overdue':''}`}>{!t.due?'No deadline':t.due===dateKey()?'Today':new Date(t.due+'T00:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:new Date(t.due+'T00:00:00').getFullYear()!==new Date().getFullYear()?'numeric':undefined})}</span><button className="more" aria-label={`Edit ${t.title}`} onClick={()=>edit(t)}><Pencil size={16}/></button><button className="more" aria-label={`Delete ${t.title}`} onClick={()=>remove(t.id)}><Trash2 size={16}/></button></div>;
 return <div className="app"><aside className="sidebar"><div className="brand"><img className="site-logo" src="/karibok-logo.png" alt="KARIBOK" /><div className="brand-sub">study • work • hustle</div></div><div className="nav-label">YOUR WORKSPACE</div><nav>{[["Dashboard",LayoutDashboard],["Tasks",CheckSquare],["Projects",FolderKanban],["Calendar",CalendarDays],["Focus",Timer],["Analytics",BarChart3],["Clients",Users],["Finances",WalletCards],["Notifications",Bell],["Settings",Settings]].map(([name,Icon])=><button key={name} aria-label={name} className={`nav-item ${page===name?'active':''}`} onClick={()=>setPage(name)}><Icon size={18}/><span>{name}</span></button>)}</nav><div className="sidebar-bottom"><div className="mini-card"><Sparkles size={16}/><div><strong>Keep moving.</strong><span>Isa-isa lang, uusad din.</span></div></div><button className="profile w-full text-left" onClick={()=>setPage('Settings')}>{avatar}<div><strong>{data.name}</strong><span>Personal workspace</span></div></button></div></aside><main className="main"><header className="topbar"><div className="search"><Search size={18}/><input aria-label="Search tasks" placeholder="Search your tasks…" value={query} onChange={e=>{setQuery(e.target.value);if(page!=='Dashboard'&&page!=='Tasks')setPage('Tasks');}}/></div><button className="user-pill" onClick={()=>setPage('Settings')}>{avatar}<span>{data.name}</span></button></header><div className="content">
 {data.timer&&page!=='Focus'&&<button className="timer-banner" onClick={()=>setPage('Focus')}><Timer size={16}/> {data.timer.startedAt?'Timer running':'Timer paused'} · {data.timer.label}<span>Open timer →</span></button>}
 {page==='Calendar'?<CalendarPage data={data} onEdit={edit} onAdd={due=>setEditor({id:crypto.randomUUID(),title:'',category:data.categories[0],project:'',projectId:'',recurrence:'none',priority:'Medium',due,progress:0})}/>:
 page==='Focus'?<FocusPage data={data} update={update} now={now} notify={setMessage}/>:
 page==='Analytics'?<AnalyticsPage data={data}/>:
 page==='Notifications'?<NotificationsPage data={data} update={update} onEdit={edit} notify={setMessage}/>:
 page==='Finances'?<FinancePage data={data} update={update} notify={setMessage}/>:
 ['Clients','Projects'].includes(page)?<WorkPage key={page} page={page} data={data} update={update} notify={setMessage} renderTask={row} onAddTask={project=>setEditor({id:crypto.randomUUID(),title:'',category:project.category||data.categories[0],project:project.title,projectId:project.id,recurrence:'none',priority:'Medium',due:project.deadline||'',progress:0})}/>:
 <> {page!=='Settings'?<><section className="hero"><div><div className="eyebrow">{new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'}).toUpperCase()}</div><h1>{page==='Dashboard'?<>Ala eh, <span>may gagawin.</span></>:'Your tasks, organized.'}</h1><p>{page==='Dashboard'?'A little progress goes a long way. Make room for what matters.':'School, work, and everything in between.'}</p></div><button className="primary" onClick={()=>edit()}><Plus size={18}/> Add task</button></section>
 {page==='Dashboard'&&<section className="stat-grid">{[['Tasks completed',`${complete}/${data.tasks.length}`,'One step closer',CircleCheck],['Due today',data.tasks.filter(t=>t.due===dateKey()&&t.progress<100).length,'Your next priorities',Clock3],['In progress',data.tasks.filter(t=>t.progress>0&&t.progress<100).length,'Keep the momentum',Layers],['Overall progress',`${average(data.tasks)}%`,'Across all your tasks',TrendingUp]].map(([title,value,note,Icon])=><div className="stat-card" key={title}><div className="stat-icon"><Icon size={19}/></div><div className="stat-title">{title}</div><div className="stat-value">{value}</div><div className="stat-note">{note}</div></div>)}</section>}
 <div className={page==='Dashboard'?'dashboard-grid':'task-page'}><section className="panel tasks-panel"><div className="panel-head"><div><div className="eyebrow">{page==='Dashboard'?'MAKE IT HAPPEN':'YOUR LIST'}</div><h2>What's on your plate?</h2></div><span className="muted text-xs">{tasks.length} tasks</span></div><div className="flex flex-wrap gap-2 mb-4">{['All',...data.categories].map(c=><button key={c} className={`filter ${filter===c?'selected':''}`} onClick={()=>setFilter(c)}>{c}</button>)}</div><div className="task-list">{tasks.length?tasks.map(row):<div className="empty"><CheckSquare size={30}/><h3>A little breathing room.</h3><p>{data.tasks.length?'No tasks match this view. Try another category or search.':'Add your first task to get started.'}</p></div>}</div></section>
 {page==='Dashboard'&&<section className="panel"><div className="panel-head"><div><div className="eyebrow">THE BIGGER PICTURE</div><h2>Your progress</h2></div><TrendingUp size={19}/></div>{data.categories.map(c=>{const list=data.tasks.filter(t=>t.category===c);return <div className="progress-stat" key={c}><div><span>{c} <small className="muted">({list.length})</small></span><strong>{average(list)}%</strong></div><div className="progress-track"><div className="progress-fill" style={{width:`${average(list)}%`}}/></div></div>})}<div className="quote">“Hindi kailangan mabilis. Kailangan lang umusad.”</div></section>}</div><p className="local-note">{workspace.status} · Your personal space to make progress</p></>:
 <><section className="page-head"><div><div className="eyebrow">MAKE YOURSELF AT HOME</div><h1>Personal, like you.</h1><p>Your profile. Your colors. Your kind of workspace.</p></div><span className="tag">Preferences save automatically</span></section><div className="settings-grid"><section className="panel settings-panel"><h2>Profile</h2><p className="muted">A familiar face in your workspace.</p><div className="flex items-center gap-4 my-6"><div className="profile-large">{avatar}</div><label className="secondary cursor-pointer flex items-center gap-2"><Upload size={16}/> Change picture<input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/></label>{data.photo&&<button className="text-btn" onClick={()=>update({photo:''})}>Remove</button>}</div><p className="muted text-xs">JPG, PNG, or WebP. Maximum 2 MB.</p><label className="field">Display name<input maxLength={40} value={data.name} onChange={e=>update({name:e.target.value})} onBlur={()=>{if(!data.name.trim())update({name:'Student'});}}/></label></section><section className="panel settings-panel"><h2>Appearance</h2><p className="muted">Set the mood for your next good idea.</p><label className="field">Theme</label><div className="flex gap-2">{[['system',Monitor],['light',Sun],['dark',Moon]].map(([theme,Icon])=><button aria-pressed={data.theme===theme} key={theme} className={`theme-option ${theme===data.theme?'selected':''}`} onClick={()=>update({theme})}><Icon size={20}/>{theme}</button>)}</div><label className="field">Accent color</label><div className="flex flex-wrap items-center gap-3">{['#8b3f2f','#526b51','#6253a3','#2563eb','#be416b','#d39836'].map(c=><button className="swatch" key={c} aria-label={`Use ${c} accent`} aria-pressed={data.accent===c} style={{background:c,outline:data.accent===c?'2px solid var(--text)':'none'}} onClick={()=>update({accent:c})}/>)}<input aria-label="Custom accent color" type="color" value={data.accent} onChange={e=>update({accent:e.target.value})}/><span className="muted text-xs">{data.accent.toUpperCase()}</span></div><div className="appearance-preview"><span className="tag">Your accent, everywhere</span><div className="progress-track my-4"><div className="progress-fill" style={{width:'68%'}}/></div><button className="primary" onClick={()=>setPage('Dashboard')}>See your dashboard</button></div></section><CategoryManager data={data} update={update} notify={setMessage}/><AccountPanel workspace={workspace} notify={setMessage}/></div></>}
 </>}
 </div></main>{message&&<div className="toast" role="status">{message}<button aria-label="Dismiss notification" onClick={()=>setMessage('')}><X size={16}/></button></div>}{editor&&<TaskModal task={editor} setTask={setEditor} categories={data.categories} projects={data.projects} editing={data.tasks.some(t=>t.id===editor.id)} onClose={()=>setEditor(null)} onSave={e=>{e.preventDefault();if(!editor.title.trim())return;update(d=>saveTask(d,{...editor,title:editor.title.trim()}));setEditor(null);}}/>}</div>;
}
function TaskModal({task,setTask,categories,projects,editing,onClose,onSave}){const ref=useRef(null);useEffect(()=>{const previous=document.activeElement;ref.current.showModal();return()=>previous?.focus();},[]);const change=(key,value)=>setTask({...task,[key]:value});return <dialog ref={ref} className="modal" onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-head"><div><div className="eyebrow">{editing?'A LITTLE ADJUSTMENT':'ONE STEP FORWARD'}</div><h2>{editing?'Edit task':'Add something to the list'}</h2></div><button className="icon-btn" aria-label="Close task editor" onClick={onClose}><X size={18}/></button></div><form onSubmit={onSave}><label>Task title<input autoFocus required maxLength={150} value={task.title} onChange={e=>change('title',e.target.value)} placeholder="What do you want to get done?"/></label><label>Project (optional)<select value={task.projectId||''} onChange={e=>setTask({...task,projectId:e.target.value,project:projects.find(p=>p.id===e.target.value)?.title||''})}><option value="">No project</option>{projects.map(p=><option value={p.id} key={p.id}>{p.title}</option>)}</select></label><div className="form-grid"><label>Category<select value={task.category} onChange={e=>change('category',e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Priority<select value={task.priority} onChange={e=>change('priority',e.target.value)}>{['Low','Medium','High'].map(c=><option key={c}>{c}</option>)}</select></label></div><label>Repeat<select value={task.recurrence||'none'} onChange={e=>change('recurrence',e.target.value)}><option value="none">Does not repeat</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label>Deadline<input required={task.recurrence!=='none'} type="date" value={task.due} onChange={e=>change('due',e.target.value)}/></label><label>Progress · {task.progress}%<input type="range" min="0" max="100" step="5" value={task.progress} onChange={e=>change('progress',Number(e.target.value))}/></label><div className="modal-actions"><button className="secondary" type="button" onClick={onClose}>Cancel</button><button className="primary" type="submit">{editing?'Save changes':'Add task'}</button></div></form></dialog>}
createRoot(document.getElementById('root')).render(<App/>);








