import React,{useState,useEffect} from 'react';
import {Plus,Star,Folder,Archive,Trash2,Pencil,ArrowLeft,RotateCcw,StickyNote,Users} from 'lucide-react';
import {Heading,Empty,Dialog} from './features';
import {Field,RecordActions} from './v4ui';
import {saveFolder,trashRecord,restoreRecord,permanentlyDelete,trashKinds} from './organize';
import {dayKey} from './domain';
import {validateClient,CLIENT_TYPES,upsert} from './v4';

export function Relationships({data,value,onChange}){return <div className="form-grid"><Field label="Folder" value={value.folderId||''} onChange={folderId=>onChange({...value,folderId})} options={[{value:'',label:'No Folder'},...data.folders.map(f=>({value:f.id,label:`${f.parentId?(data.folders.find(p=>p.id===f.parentId)?.name+' / '):''}${f.name}${f.archived?' (archived)':''}`}))]}/><Field label="Client" value={value.clientId||''} onChange={clientId=>onChange({...value,clientId})} options={[{value:'',label:'No Client'},...(value.clientId&&!data.clients.some(c=>c.id===value.clientId)?[{value:value.clientId,label:'Client in Trash'}]:[]),...data.clients.map(c=>({value:c.id,label:c.name}))]}/></div>}

export function OrganizePage({page,data,raw,update,renderTask,onAddTask,onNote,quickAdd,onQuickAddHandled}){
 const [selected,setSelected]=useState(null),[editor,setEditor]=useState(null),[error,setError]=useState(''),[archived,setArchived]=useState(false),[deleting,setDeleting]=useState(null);
 const create=()=>{setError('');setEditor(page==='Clients'?{id:crypto.randomUUID(),name:'',email:'',contactPerson:'',phone:'',type:'',notes:''}:{id:crypto.randomUUID(),name:'',parentId:selected&&data.folders.find(f=>f.id===selected&&!f.parentId)?selected:'',favorite:false,archived:false});};
 useEffect(()=>{if(quickAdd?.kind==='client'&&page==='Clients'||quickAdd?.kind==='folder'&&page==='Folders'){create();onQuickAddHandled?.();}},[quickAdd]);
 const folder=data.folders.find(f=>f.id===selected),client=data.clients.find(c=>c.id===selected);
 const context=page==='Clients'?{clientId:client?.id||''}:{folderId:folder?.id||''};
 const notes=list=>list.length?<div className="records-grid">{list.map(n=><article className="panel" key={n.id}><div className="record-title"><h3 className="icon-label"><StickyNote/>{n.title}</h3><RecordActions label={n.title} onEdit={()=>onNote(n)} onDelete={()=>update(d=>trashRecord(d,'notes',n.id))}/></div><p className="v4-notes">{n.body}</p></article>)}</div>:<Empty>No notes yet.</Empty>;
 const taskGroup=(title,list)=><section className="panel mt-4" key={title}><h2>{title}</h2>{list.length?list.map(renderTask):<Empty>No {title.toLowerCase()}.</Empty>}</section>;
 const folderCard=f=><article className="panel work-card" key={f.id}><div className="record-title"><h2><button className="title-link" onClick={()=>setSelected(f.id)}><Folder size={18}/>{f.name}</button></h2><RecordActions label={f.name} onEdit={()=>{setError('');setEditor({...f});}} onDelete={()=>{update(d=>trashRecord(d,'folders',f.id));setSelected(null);}}/></div><p className="muted">{f.parentId?`Subfolder of ${data.folders.find(p=>p.id===f.parentId)?.name}`:'Folder'} · {data.tasks.filter(t=>t.folderId===f.id).length} tasks · {data.notes.filter(n=>n.folderId===f.id).length} notes</p><div className="flex gap-2 mt-4"><button className="secondary" aria-pressed={!!f.favorite} aria-label={`${f.favorite?'Unfavorite':'Favorite'} ${f.name}`} onClick={()=>update(d=>saveFolder(d,{...f,favorite:!f.favorite}))}><Star size={16}/></button><button className="secondary" onClick={()=>update(d=>saveFolder(d,{...f,archived:!f.archived}))}><Archive size={16}/> {f.archived?'Unarchive':'Archive'}</button></div></article>;
 if(page==='Trash')return <><Heading eyebrow="RECOVERY" title="Trash" description="Items stay here until you restore or permanently delete them."/>{trashKinds.map(kind=>{const items=raw[kind].filter(r=>r.deletedAt);return items.length?<section className="panel mt-4" key={kind}><h2>{kind[0].toUpperCase()+kind.slice(1)}</h2>{items.map(r=><div className="record-row" key={r.id}><span>{r.title||r.name||r.description||r.person||'Record'}<small className="muted"> · {new Date(r.deletedAt).toLocaleDateString()}</small></span><div className="flex gap-2"><button className="secondary" onClick={()=>update(d=>restoreRecord(d,kind,r.id))}><RotateCcw/>Restore</button><button className="secondary" onClick={()=>setDeleting({kind,record:r})}><Trash2/>Delete Permanently</button></div></div>)}</section>:null;})}{!trashKinds.some(k=>raw[k].some(r=>r.deletedAt))&&<Empty>Trash is empty.</Empty>}{deleting&&<Dialog title="Delete permanently?" submitLabel="Delete Permanently" onClose={()=>setDeleting(null)} onSubmit={e=>{e.preventDefault();try{update(d=>permanentlyDelete(d,deleting.kind,deleting.record.id));setDeleting(null);}catch(e){setError(e.message);}}}><p>This permanently deletes {deleting.record.name||deleting.record.title||'this record'}{deleting.kind==='folders'?' and all its contents and subfolders':''}. This cannot be undone.</p>{error&&<p role="alert">{error}</p>}</Dialog>}</>;
 const detail=page==='Clients'?client:folder;
 const linked=data.tasks.filter(t=>page==='Clients'?t.clientId===client?.id:t.folderId===folder?.id);
 return <>
 {selected&&<button className="text-btn" onClick={()=>setSelected(folder?.parentId||null)}><ArrowLeft/>Back</button>}
 <Heading eyebrow={page.toUpperCase()} title={detail?.name||page} description={page==='Clients'?'Tasks and notes, connected directly to your clients.':page==='Notes'?'Your ideas, all in one place.':'Organize your work without duplicating it.'} action={<div className="flex gap-2">{page!=='Notes'&&page!=='Favorites'&&!folder?.parentId&&<button className="primary" onClick={create}><Plus size={17}/>{page==='Clients'?'Add client':folder?'Add subfolder':'New folder'}</button>}{(detail||page==='Notes')&&<button className="secondary" onClick={()=>onNote({id:crypto.randomUUID(),title:'',body:'',...context})}>Add note</button>}{detail&&<button className="primary" onClick={()=>onAddTask(context)}>Add task</button>}</div>}/>
 {page==='Notes'?notes(data.notes):page==='Clients'?client?<><section className="panel"><div className="record-title"><h2>Client details</h2><RecordActions label={client.name} onEdit={()=>{setError('');setEditor({...client});}} onDelete={()=>{update(d=>trashRecord(d,'clients',client.id));setSelected(null);}}/></div><p>{[client.contactPerson,client.email,client.phone,client.type].filter(Boolean).join(' · ')}</p><p className="v4-notes">{client.notes}</p></section>{taskGroup('Active tasks',linked.filter(t=>t.progress<100))}{taskGroup('Completed tasks',linked.filter(t=>t.progress===100))}{taskGroup('Upcoming tasks',linked.filter(t=>t.progress<100&&t.due>=dayKey()).sort((a,b)=>a.due.localeCompare(b.due)))}<h2 className="mt-4">Notes</h2>{notes(data.notes.filter(n=>n.clientId===client.id))}</>:<div className="records-grid">{data.clients.map(c=><article className="panel work-card" key={c.id}><div className="record-title"><h2><button className="title-link" onClick={()=>setSelected(c.id)}><Users/>{c.name}</button></h2><RecordActions label={c.name} onEdit={()=>{setError('');setEditor({...c});}} onDelete={()=>update(d=>trashRecord(d,'clients',c.id))}/></div><p>{c.email}</p><p className="muted">{data.tasks.filter(t=>t.clientId===c.id&&!t.deletedAt).length} tasks</p></article>)}{!data.clients.length&&<Empty>No clients yet.</Empty>}</div>:<>
 <div className="flex gap-2 mb-4"><button className={`filter ${!archived?'selected':''}`} onClick={()=>setArchived(false)}>Active</button><button className={`filter ${archived?'selected':''}`} onClick={()=>setArchived(true)}>Archived</button></div>
 {folder&&<div className="mb-4">{folderCard(folder)}</div>}
 <div className="records-grid">{data.folders.filter(f=>Boolean(f.archived)===archived&&(page==='Favorites'?f.favorite:((f.parentId||null)===selected))).map(folderCard)}</div>
 {folder&&<>{taskGroup('Tasks',linked)}<h2 className="mt-4">Notes</h2>{notes(data.notes.filter(n=>n.folderId===folder.id))}</>}
 {!folder&&page==='Folders'&&<>{taskGroup('No Folder',data.tasks.filter(t=>!t.folderId))}<h2 className="mt-4">Notes with No Folder</h2>{notes(data.notes.filter(n=>!n.folderId))}</>}
 </>}
 {editor&&<Dialog title={page==='Clients'?'Client details':'Folder details'} submitLabel={page==='Clients'?'Save Client':'Save Folder'} onClose={()=>setEditor(null)} onSubmit={e=>{e.preventDefault();try{if(page==='Clients'){const value={...editor,name:editor.name.trim(),email:editor.email.trim()};validateClient(value);update(d=>upsert(d,'clients',value));}else update(d=>saveFolder(d,editor));setEditor(null);}catch(e){setError(e.message);}}}><Field label={page==='Clients'?'Client / Business Name':'Folder name'} required value={editor.name} onChange={name=>setEditor({...editor,name})}/>{page==='Clients'?<>{['contactPerson','email','phone'].map(key=><Field key={key} label={{contactPerson:'Contact Person',email:'Email',phone:'Phone'}[key]} type={key==='email'?'email':'text'} value={editor[key]} onChange={v=>setEditor({...editor,[key]:v})}/>)}<Field label="Client Type" value={editor.type} options={['',...CLIENT_TYPES]} onChange={type=>setEditor({...editor,type})}/><Field label="Notes" multiline value={editor.notes} onChange={notes=>setEditor({...editor,notes})}/></>:<Field label="Parent folder" value={editor.parentId||''} onChange={parentId=>setEditor({...editor,parentId})} options={[{value:'',label:'Top level'},...data.folders.filter(f=>!f.parentId&&f.id!==editor.id&&!data.folders.some(c=>c.parentId===editor.id)).map(f=>({value:f.id,label:f.name}))]}/>}{error&&<p role="alert">{error}</p>}</Dialog>}
 </>;
}
