import React,{useState} from 'react';
import {Dialog,Empty} from './features';
import {Field,RecordActions,DeleteDialog,Metrics,centsMoney} from './v4ui';
import {id,dayKey} from './domain';
import {parseCents,upsert} from './v4';
import {debtStatus,debtSummary,validateDebt} from './utang';
export function UtangPage({data,update}){
 const [edit,setEdit]=useState(null),[payment,setPayment]=useState(null),[remove,setRemove]=useState(null),[error,setError]=useState('');
 const summary=debtSummary(data,dayKey());const change=(k,v)=>setEdit(e=>({...e,[k]:v}));
 const open=d=>{setError('');setEdit({...d,amount:(d.amountCents/100).toFixed(2)});};
 const pay=(d,full=false)=>{setError('');setPayment({debtId:d.id,id:id(),amount:full?(debtStatus(d).remaining/100).toFixed(2):'',accountId:data.accounts[0]?.id||'',date:dayKey(),full});};
 const options=[{value:'',label:'Choose account'},...data.accounts.map(a=>({value:a.id,label:a.name}))];
 return <><div className="panel-head"><div><h2>Utang</h2><p className="muted text-sm">Keep money owed separate from everyday spending.</p></div><button className="primary" onClick={()=>open({id:id(),direction:'receivable',person:'',amountCents:0,date:dayKey(),dueDate:'',reason:'',notes:'',accountId:'',repayments:[]})}>Add Utang</button></div>
 <Metrics items={[["Total owed to me",centsMoney(summary.owedToMe)],["Total I owe",centsMoney(summary.iOwe)],["Overdue amount",centsMoney(summary.overdue)],["Unpaid records",summary.unpaid]]}/>
 {['receivable','payable'].map(direction=><section key={direction} className="panel mt-4"><h2>{direction==='receivable'?"Utang sa’yo":"Utang mo"}</h2><p className="muted text-sm">{direction==='receivable'?'Money other people owe you':'Money you owe other people'}</p>{!(data.utang||[]).some(d=>d.direction===direction)?<Empty>No records yet. Add Utang to start tracking money owed.</Empty>:(data.utang||[]).filter(d=>d.direction===direction).map(d=>{const s=debtStatus(d);return <article className="debt-card" key={d.id}><div className="record-title"><h2>{d.person}</h2><RecordActions label={`Utang ${d.person}`} onEdit={()=>open(d)} onDelete={()=>setRemove({debtId:d.id,label:d.person})}/></div><span className="tag">{s.status}</span><p className="v4-notes">{d.reason}</p><p className="muted text-xs">Borrowed {d.date}{d.dueDate?` · Due ${d.dueDate}`:''}{d.dueDate&&d.dueDate<dayKey()&&s.remaining>0?' · Overdue':''}</p><Metrics items={[["Original amount",centsMoney(d.amountCents)],["Paid",centsMoney(s.paid)],["Remaining",centsMoney(s.remaining)]]}/><div className="project-progress-label"><span>Repayment progress</span><strong>{s.progress}%</strong></div><div className="progress-track"><div className="progress-fill" style={{width:s.progress+'%'}}/></div>{d.notes&&<p className="v4-notes">{d.notes}</p>}{s.remaining>0&&<div className="v4-actions mt-4"><button className="primary" onClick={()=>pay(d)}>Record Payment</button><button className="secondary" onClick={()=>pay(d,true)}>Mark as Paid</button></div>}{d.repayments.length>0&&<details className="mt-4"><summary>Repayment history</summary>{d.repayments.map(p=><div className="ledger-row" key={p.id}><div className="ledger-description"><strong>{centsMoney(p.amountCents)}</strong><span>{p.date} · {data.accounts.find(a=>a.id===p.accountId)?.name}</span></div><button className="text-btn" aria-label={`Delete repayment ${d.person} ${p.date}`} onClick={()=>setRemove({debtId:d.id,paymentId:p.id,label:'repayment'})}>Delete</button></div>)}</details>}</article>;})}</section>)}
 {edit&&<Dialog title="Utang details" wide submitLabel="Save Utang" onClose={()=>setEdit(null)} onSubmit={e=>{e.preventDefault();try{const d={...edit,amountCents:parseCents(edit.amount)};delete d.amount;update(current=>{validateDebt(d,current);return upsert(current,'utang',d);});setEdit(null);}catch(e){setError(e.message);}}}><Field label="Direction" value={edit.direction} onChange={v=>change('direction',v)} options={[{value:'receivable',label:'Someone owes me'},{value:'payable',label:'I owe someone'}]}/><Field label="Person name" required value={edit.person} onChange={v=>change('person',v)}/><Field label="Amount (PHP)" required value={edit.amount} onChange={v=>change('amount',v)}/><div className="form-grid"><Field label="Date borrowed" type="date" required value={edit.date} onChange={v=>change('date',v)}/><Field label="Due date" type="date" value={edit.dueDate} onChange={v=>change('dueDate',v)}/></div><Field label="Reason" required value={edit.reason} onChange={v=>change('reason',v)}/><Field label="Notes" multiline value={edit.notes} onChange={v=>change('notes',v)}/><Field label={edit.direction==='receivable'?'Originally lent from':'Originally borrowed into'} value={edit.accountId} onChange={v=>change('accountId',v)} options={[{value:'',label:'Historical record — no balance adjustment'},...options.slice(1)]}/><p className="muted text-sm">Choose an account to record the original money movement. For an older debt already included in your starting balance, leave this unset. Status updates automatically from repayments.</p>{error&&<p role="alert">{error}</p>}</Dialog>}
 {payment&&<Dialog title={payment.full?'Mark as Paid':'Record Payment'} submitLabel="Save Repayment" onClose={()=>setPayment(null)} onSubmit={e=>{e.preventDefault();try{update(current=>{const d=current.utang.find(d=>d.id===payment.debtId);if(!d)throw Error('This Utang is no longer available.');const next={...d,repayments:[...d.repayments,{id:payment.id,amountCents:parseCents(payment.amount),accountId:payment.accountId,date:payment.date}]};validateDebt(next,current);return upsert(current,'utang',next);});setPayment(null);}catch(e){setError(e.message);}}}><Field label="Repayment amount (PHP)" required value={payment.amount} onChange={v=>setPayment({...payment,amount:v})}/><Field label={data.utang.find(d=>d.id===payment.debtId)?.direction==='receivable'?'Received via':'Paid from'} required options={options} value={payment.accountId} onChange={v=>setPayment({...payment,accountId:v})}/><Field label="Payment date" type="date" required value={payment.date} onChange={v=>setPayment({...payment,date:v})}/><p className="muted text-sm">This records an actual payment and updates the selected account. It is excluded from normal income and expenses.</p>{!data.accounts.length&&<p role="alert">Add an account in Accounts first.</p>}{error&&<p role="alert">{error}</p>}</Dialog>}
 {remove&&<DeleteDialog label={remove.label} description="This reverses the related account movement. Deleting an Utang also removes its repayments." onClose={()=>setRemove(null)} onDelete={()=>{update(current=>({...current,utang:remove.paymentId?current.utang.map(d=>d.id===remove.debtId?{...d,repayments:d.repayments.filter(p=>p.id!==remove.paymentId)}:d):current.utang.filter(d=>d.id!==remove.debtId)}));setRemove(null);}}/>}
 </>;
}
